### ISSUE TITLE
如何加入阅后即焚功能

### ISSUE THREAD

**Issue by fakeyee** [AwakenDragon/EaseMobDIYUI#2]
楼主你好，看了你封装的环信UI，很nice啊，想在你的基础上加入阅后即焚的功能进来，效果做成和阿里的来往类似，还望楼主指点一二，多谢  :-)

**Comment by AwakenDragon** [comment]
阅后即焚就是一种特殊的消息类型，用一个字段来标记已读未读，读了就删掉。我觉得关键是怎么确定这个已读和未读，环信的message里虽然有标记已读和未读的字段，但是并不能确定用户到底真的有没有看过这条消息，所以不可取。所以我觉得一般的做法是，一开始不显示消息的具体内容，让用户主动去点击这条消息来进行阅读，这样更容易确定已读还是未读。当用户点击消息后，通过定时或者用户主动退出阅读的方式来确定已读完，然后删除这条消息便可。来往我也没怎么用过，所以我也不清楚它的实现方式是什么样的。
